<table class="generic-table">
    <caption>Vous avez choisi...</caption>
    <thead>
    <tr>
        <th>Photo</th>
        <th>Description</th>
    </tr>
    </thead>
    <tbody class="meal-list">
    <tr>
        <td>
            <img alt="<?= $product['name'] ?>"
                 src="<?= $wwwUrl ?>/images/meals/<?= $product['photo'] ?>">
        </td>
        <td>
            <h3><?= $product['name'] ?></h3>
            <p><?= $product['description'] ?></p>

            <p><?= $product['category'] ?></p>
            <p><?= number_format($product['salePrice'], 2) ?> €</p>
        </td>
    </tbody>
</table
