<!--page de commande -->

<h2><i class="fa fa-shopping-cart"></i> Passer une commande</h2>
<form class="generic-form" action="<?= $requestUrl ?>/order/OrderSucess" method="post">


    <!--    Début du formulaire  -->
    <fieldset>
        <legend>Ajouter un article</Informa></legend>
        <!--    Pour les messages d'erreur -->
        <aside id="error-message" class="error-message hidden">
            <h3><i class="fa fa-warning"></i> Il y a <em class="total-error-count">1</em> erreur(s) dans le formulaire !
            </h3>
            <p></p>
        </aside>
        
        
        <ul>
            <li class="basket-empty">Veuillez choisir un produit</li>
            <li>
                <label for="productName">Nom du produit :</label>
                <select id="productList" name="productName">
                        <option value="choisir">Veuillez choisir un produit</option>
                    <?php foreach ($products as $product) : ?>
                        <option value="<?= $product['id'] ?>"><?= $product['name'] ?> - <?= $product['salePrice'] ?>€</option>
                    <?php endforeach ?>
                </select>

                <div id="target" class="hide-product meal-details no-left-label">
                    <!-- Contenu dynamique en AJAX -->
                </div>
            </li>
            <li class="hide-product">
                <label for="quantity">Quantité : </label>
                <input class="quantity" type="text" min="0" id="quantity" name="quantity" maxlength="2" class="quantity">
                <!-- TODO: Message d'erreur si les quantité sont superieur-->
            </li>
            <li>
                <button id="add-product" class="hide-product button button-primary no-left-label"><i class="fa fa-cart-arrow-down"></i> Ajouter</button>
            </li>
        </ul>
    </fieldset>
    <fieldset id="summary" class="hide-summary">
        <legend>Récapitulatif de la commande</Informa></legend>
        <table class="generic-table">
            <thead>
            <tr>
                <th>Quantité</th>
                <th>Produit</th>
                <th>Prix Unitaire</th>
                <th>Prix Total</th>
            </tr>
            </thead>
            <tbody id="product-added">
            <!-- Contenu dynamique en AJAX -->
            </tbody>
        </table>
    </fieldset>
    <ul>
        <li>
            <a class="button button-cancel" href="<?= $requestUrl ?>"><i class="fa fa-times"></i> Annuler</a>
            <button id="delete-all" class="hide-summary button button-cancel" type="submit"><i class="fa fa-trash"></i> Tout supprimer</button>
            <button id="validate-form" class="hide-summary button button-primary layout-right" type="submit"><i class="fa fa-check"></i> Valider la commande</button>
        </li>
    </ul>
